---
title: "Introducción"
numbered: true
---

La presente investigación nace de la motivación por estudiar las disparidades socioeconómicas y territoriales entre las áreas urbanas y rurales en Chile ya que estas continúan siendo un desafío estructural para el desarrollo del país. Las brechas en la calidad de vida no solo se manifiestan en los ingresos monetarios, sino de manera crítica en las condiciones habitacionales y en el acceso a servicios básicos dentro del hogar [@ducci2008]. En este sentido, este estudio aborda esta problemática centrándose en dos dimensiones fundamentales: el hacinamiento y el acceso a saneamiento básico. 

Frente a esto, la investigación plantea la siguiente pregunta central: ¿Cuáles son las diferencias en las situaciones de hacinamiento y de acceso a saneamiento básico de los hogares en las zonas rurales respecto de las zonas urbanas en Chile?.
Para responder, el objetivo general de este estudio es analizar las diferencias en las condiciones de hacinamiento y acceso a saneamiento básico entre hogares de zonas urbanas y rurales en Chile, a partir de los datos de la Encuesta CASEN 2024. Y en este sentido, los objetivos específicos contemplan: describir la proporción de hogares en situación de hacinamiento en zonas urbanas y rurales de Chile; comparar el acceso a saneamiento adecuado entre hogares urbanos y rurales; y evaluar si las diferencias observadas en hacinamiento y saneamiento entre zonas urbanas y rurales son estadísticamente significativas.

La contribución esperada de este proyecto abierto es aportar evidencia empírica reciente que pueda contribuir a la discusión pública, así como en la profundización de políticas habitacionales focalizadas territorialmente. De este modo, la estructura del documento se organiza de forma lógica para dar cuenta de este proceso: Se comienza con la presente sección introductoria, continua con los antecedentes que presenta el respaldo teorico y empirico de esta investigación, posteriormente la presentación de las hipótesis, seguido de los métodos y sus resultados, para finalmente finalizar con las conclusiones.

Para poder cumplir con las interrogantes y los objetivos, el proyecto se organiza mediante una justificación teórica y empírica de la problemática, un sección de hipótesis, una explicación de los métodos utilizados, seguido de sus resultados y finalmente una discusión de los hallazgos. Asimismo, se espera que esta investigación pueda contribuir a caracterizar esta problemática y sirva de respaldo empírico para la toma de decisiones en políticas públicas. 